language: python
env:
  - ENV=ci
addons:
  apt:
    packages:
      - libudev-dev
      - libusb-1.0-0-dev
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pipenv==11.1.3
  - pipenv install --dev --skip-lock
  - pip install -e .
script:
  - python -m unittest discover
os:
  - linux
